#!/bin/bash

#Environment Variable
export TERMINAL=/usr/bin/kitty export BROWSER=/usr/bin/brave
export FILE_EXPLORER=/usr/bin/ranger
export EDITOR=/usr/bin/vim
export WALLPAPER_LOC=~/Danh/Wallpaper

#Startup Script
sxhkd &
compton --config ~/.config/compton/compton.conf &
pkill polybar > /dev/null 2>&1; ~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
wal -R

#Remove All Previous Rules to Prevent Doubling
bspc rule -r "*"

#Create Desktops for every single monitor
monitors=$(xrandr -q | grep -w connected | cut -d ' ' -f 1)
for m in $monitors 
do
	bspc monitor $m -d 1 2 3 4 5 0
done

### Startup initialization ###
##### Discord Rule and Launch
bspc rule -a discord desktop=0 monitor=$(xrandr -q | grep primary | cut -d ' ' -f 1)
pgrep Discord || /usr/bin/discord &

##### Caprine Rule and Launch
bspc rule -a caprine desktop=0 monitor=$(xrandr -q | grep primary | cut -d ' ' -f 1)
pgrep caprine || /usr/bin/caprine &

### App rule
bspc rule -a Zathura state=tiled

#Refocus desktop
bspc desktop -f 1

#On hover focus
bspc config focus_follows_pointer true

#bspwm configuration
bspc config top_padding 62
bspc config border_width 1
bspc config window_gap 11
bspc config focused_border_color \#FFFFFF

#Configuration for dropdown terminal
#bspc rule -a '_dropdownTerminal' sticky=on state=floating hidden=on -f
#if ! xdotool search --class _dropdownTerminal; then
#	kitty --class _dropdownTerminal &
#fi
