#!/bin/bash

#Set cursor shape
which xsetroot >/dev/null 2>&1 && xsetroot -cursor_name left_ptr &

#Run xbindkeys to bind mouse keys xbindkeys
which xbindkeys >/dev/null 2>&1 && xbindkeys
 
#Increase keyboard output rate
which xset >/dev/null 2>&1 && xset r rate 170 14

#Remove All Previous Rules to Prevent Doubling
bspc rule -r "*"

#Create Desktops for every single monitor
monitors=$(xrandr -q | grep -w connected | cut -d ' ' -f 1)
for m in $monitors 
do
	bspc monitor $m -d 1 2 3 4 5 0
done

### App rule
bspc rule -a Zathura state=tiled

#Refocus desktop
bspc desktop -f 1

#On hover focus
bspc config focus_follows_pointer true

#bspwm configuration
bspc config top_padding 62
bspc config border_width 1
bspc config window_gap 11
bspc config focused_border_color \#FFFFFF

### Startup initialization ###
##### Discord Rule and Launch
bspc rule -a discord desktop=0 monitor=`xrandr | grep primary | cut -d' ' -f1`
#pgrep Discord || /usr/bin/discord &

##### Caprine Rule and Launch
bspc rule -a Caprine desktop=0 monitor=`xrandr | grep primary | cut -d' ' -f1`
#pgrep caprine || /usr/bin/caprine &
